version: 2.1
jobs:
  semantic_version:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: release
          command: npm run semantic-release || true
             
workflows:
    build-and-test:
      jobs:
        - semantic_version
        
