orbs:
 aws-ecr: circleci/aws-ecr@6.7.1
version: 2.1
jobs:
  semantic_version:
   executor: aws-ecr/default
   steps:
        - checkout
        - run: 
             name: install the node and npm
             command: |
                curl -sL https://deb.nodesource.com/setup_10.x | bash -
                apt install nodejs && node -v && npm -v
             
workflows:
    build-and-test:
      jobs:
        - semantic_version
        
