version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.1
jobs:
  build-and-test:
    executor:
      name: aws-ecr/default
    steps:
      - checkout
      - run: aws --version
      - run: docker -v

workflows:
    build-and-test:
      jobs:
        - build-and-test
