version: 2.1
jobs:
  semantic_version:
   docker:
     - image: google/cloud-sdk
   steps:
        - checkout
             
workflows:
    build-and-test:
      jobs:
        - semantic_version
        
