orbs:
  aws-ecr: circleci/aws-ecr@6.7.1
  node: circleci/node@1.1.6
version: 2.1
jobs:
  sonar_verify:
       executor:
       docker:
        - image: circleci/node
       steps:
        - checkout
        - run: node -
          
          
workflows:
    build-and-test:
      jobs:
        - sonar_verify
        
