version: 2.1
jobs:
  semantic_version:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install 
      - run: 
          name: commit lint
          command: yarn commitlint-circle
      - run:
          name:  release
          command: |
             npm run semantic-release || true
      - save_cache:
          name:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: 
          name:  install  expo-cli
          command: npm install -g expo-cli
             
workflows:
    build-and-test:
      jobs:
        - semantic_version
        
