orbs:
  aws-ecr: circleci/aws-ecr@6.7.1
  node: circleci/node@1.1.6
version: 2.1
jobs:
  semantic_version:
       executor:
       docker:
        - image: circleci/node
       steps:
        - checkout
        - run: node -v
        - run: 
           name: Install dependencies
           command: npm install -g yarn && yarn install
        - save_cache:
           name: save cache
           key: yarn-packages-{{ checksum "yarn.lock" }}
           paths:
             - ~/.cache/yarn
        - run: 
           name: commit lint
           command: yarn commitlint-circle
        - run: 
           name:  install  expo-cli
           command: npm install -g expo-cli
          
workflows:
    build-and-test:
      jobs:
        - semantic_version
        
