orbs:
  aws-ecr: circleci/aws-ecr@6.7.1
  node: circleci/node@1.1.6
version: 2.1
jobs:
  semantic_version:
     docker:
      - image: google/cloud-sdk
     steps:
        - checkout
        - run:
          name: install node js  and npm
          command: | 
            curl -sL https://deb.nodesource.com/setup_10.x | bash -
            apt install nodejs && node -v && npm -v
        - restore_cache:
           name: Restore Yarn Package Cache
           keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
        - run: 
           name: Install dependencies
           command: npm install -g yarn && yarn install
        - run: 
           name: commit lint
           command: yarn commitlint-circle
        - run:
           name:  release
           command: npm run semantic-release || true
        - save_cache:
           name: cache the yarn
           key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
        - run: 
          name:  install  expo-cli
          command: npm install -g expo-cli          
workflows:
    build-and-test:
      jobs:
        - semantic_version
        
