
orbs:
  sonarcloud: extendaretail/sonarcloud@0.0.2
version: 2.1
jobs:
  sonar_verify:
       executor:
       docker: 
        - image: 'circleci/node:10'
       steps:
        - checkout
        - run: 
            name: Run Sonarqube scanner
            command: |
                    sonar-scanner  -Dsonar.projectKey=mynodeproj -Dsonar.sources=.  -Dsonar.host.url=http://35.233.231.234 -Dsonar.login=0a0eca3f1ec3dea8fbc7463036d8e7061cb956f6
 
workflows:
    build-and-check:
      jobs:
        - sonar_verify
