orbs:
        sonarcloud: extendaretail/sonarcloud@1.0.0
      version: 2.1
      workflows:
        main:
          jobs:
          - commit:
              context: sonarcloud
          - sonarcloud/check_quality_gate:
              context: sonarcloud
              requires:
              - commit
executors:
  node:
    description: |
      Docker executor with Node.
    docker:
    - image: circleci/node:10
jobs:
  check_quality_gate:
    description: |
      Wait for the scanner results. This job assumes an analysis has been
      run and will wait for SonarCloud to update the quality gate for the
      analysis.
    executor: node
    steps:
    - checkout
    - attach_workspace:
        at: .
    - check_quality_gate
version: 2.1
